# -*- coding: utf-8 -*-
"""Proyecto_Col.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EMwBk7Om_0cwqa5AnR7nxlFhQmYFPNt
"""

#Subir el archivo

from google.colab import files
import pandas as pd

uploaded = files.upload()

#Importar pandas, pathlib y matplotlib
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

# Ruta del archivo cargado en Colab
xlsx_path = "anex-ECV-Series-2024.xlsx"

# Carpeta de salida para guardar los cuadros procesados
out_dir = Path("./parsed_cuadros")   # ahora en la carpeta actual
out_dir.mkdir(parents=True, exist_ok=True)

# ---------- Funciones auxiliares ----------
def read_cuadro(sheet_name):
    """
    Lee una hoja específica del Excel y devuelve un DataFrame limpio.
    Ajusta skiprows/header según estructura de cada cuadro.
    """
    df = pd.read_excel(xlsx_path, sheet_name=sheet_name)
    print(f"Cargado {sheet_name} con {df.shape[0]} filas y {df.shape[1]} columnas")
    return df

# ---------- Leer cuadros de interés ----------
cuadro2  = read_cuadro("Cuadro 2")
cuadro5  = read_cuadro("Cuadro 5")
cuadro8  = read_cuadro("Cuadro 8")
cuadro15 = read_cuadro("Cuadro 15")
cuadro16 = read_cuadro("Cuadro 16")
cuadro17 = read_cuadro("Cuadro 17")
cuadro18 = read_cuadro("Cuadro 18")

# ---------- Guardar CSVs individuales ----------
cuadro2.to_csv(out_dir/"cuadro2.csv", index=False)
cuadro5.to_csv(out_dir/"cuadro5.csv", index=False)
cuadro8.to_csv(out_dir/"cuadro8.csv", index=False)
cuadro15.to_csv(out_dir/"cuadro15.csv", index=False)
cuadro16.to_csv(out_dir/"cuadro16.csv", index=False)
cuadro17.to_csv(out_dir/"cuadro17.csv", index=False)
cuadro18.to_csv(out_dir/"cuadro18.csv", index=False)

print("Todos los cuadros fueron exportados a ./parsed_cuadros/")

#Verificar los cuadros cargados

# Ver las primeras filas de cada cuadro
for i, df in enumerate([cuadro2, cuadro5, cuadro8, cuadro15, cuadro16, cuadro17, cuadro18], start=2):
    print(f"\n=== Vista previa Cuadro {i} ===")
    display(df.head(1))

# Ruta del archivo cargado en Colab
xlsx_path = "anex-ECV-Series-2024.xlsx"

# Carpeta de salida
out_dir = Path("./parsed_cuadros_limpios")
out_dir.mkdir(parents=True, exist_ok=True)

# ---------- Función para limpiar automáticamente ----------
def load_and_clean(sheet_name):
    """
    Lee un cuadro del Excel, detecta el inicio de la tabla,
    limpia columnas y filas vacías, y devuelve un DataFrame listo.
    """
    # Cargar con filas extra para inspeccionar
    raw = pd.read_excel(xlsx_path, sheet_name=sheet_name, header=None)

    # Detectar la primera fila que tiene al menos 2 valores no nulos
    start_row = raw.notna().sum(axis=1).idxmax()

    # Leer de nuevo usando esa fila como encabezado
    df = pd.read_excel(xlsx_path, sheet_name=sheet_name, header=start_row)

    # Eliminar columnas basura
    df = df.loc[:, ~df.columns.astype(str).str.contains("Unnamed")]

    # Eliminar filas vacías
    df = df.dropna(how="all")

    print(f"{sheet_name}: inicio en fila {start_row}, shape final {df.shape}")
    return df

# ---------- Procesar todos los cuadros ----------
cuadros = {}
for name in ["Cuadro 2","Cuadro 5","Cuadro 8","Cuadro 15","Cuadro 16","Cuadro 17","Cuadro 18"]:
    df = load_and_clean(name)
    cuadros[name] = df
    df.to_csv(out_dir / f"{name.replace(' ','_').lower()}.csv", index=False)

print(f"Todos los cuadros procesados y guardados en {out_dir}")

# Ruta donde están guardados los CSV limpios
data_dir = Path("./parsed_cuadros_limpios")

# Cargar cada cuadro en un dict
cuadro2  = pd.read_csv(data_dir/"cuadro_2.csv")
cuadro5  = pd.read_csv(data_dir/"cuadro_5.csv")
cuadro8  = pd.read_csv(data_dir/"cuadro_8.csv")
cuadro15 = pd.read_csv(data_dir/"cuadro_15.csv")
cuadro16 = pd.read_csv(data_dir/"cuadro_16.csv")
cuadro17 = pd.read_csv(data_dir/"cuadro_17.csv")
cuadro18 = pd.read_csv(data_dir/"cuadro_18.csv")

#Qué variables tiene cada cuadro

for name, df in {
    "Cuadro 2": cuadro2,
    "Cuadro 5": cuadro5,
    "Cuadro 8": cuadro8,
    "Cuadro 15": cuadro15,
    "Cuadro 16": cuadro16,
    "Cuadro 17": cuadro17,
    "Cuadro 18": cuadro18
}.items():
    print(f"\n=== {name} ===")
    print(df.head(1))

# ================================
# 1. Limpiar nombres de columnas
# ================================
for df in [cuadro2, cuadro5, cuadro8, cuadro15, cuadro16, cuadro17, cuadro18]:
    df.columns = df.columns.astype(str).str.strip()

# ================================
# 2. Renombrar y seleccionar columnas clave
# ================================

# --- Cuadro 2: Hogares con computador (zona y región) ---
cuadro2 = cuadro2.rename(columns={
    "Total nacional": "region",
    cuadro2.columns[1]: "total_hogares",
    cuadro2.columns[2]: "hogares_con_pc",
    cuadro2.columns[3]: "pct_hogares_pc"
})
df_pc = cuadro2[["region","total_hogares","hogares_con_pc","pct_hogares_pc"]]

# --- Cuadro 5: Hogares con Internet (zona y región) ---
cuadro5 = cuadro5.rename(columns={
    "Total nacional": "region",
    cuadro5.columns[1]: "total_hogares",
    cuadro5.columns[2]: "hogares_con_internet",
    cuadro5.columns[3]: "pct_hogares_internet"
})
df_internet = cuadro5[["region","total_hogares","hogares_con_internet","pct_hogares_internet"]]

# --- Cuadro 8: Hogares con computador por edad de referencia ---
cuadro8 = cuadro8.rename(columns={
    "Total nacional": "region",
    cuadro8.columns[1]: "grupo_edad",
    cuadro8.columns[2]: "total_hogares",
    cuadro8.columns[3]: "hogares_con_pc",
    cuadro8.columns[4]: "pct_hogares_pc"
})
df_pc_edad = cuadro8[["grupo_edad","total_hogares","hogares_con_pc","pct_hogares_pc"]]

# --- Cuadro 15: Matrícula/asistencia escolar ---
cuadro15 = cuadro15.rename(columns={
    "Total nacional": "region",
    cuadro15.columns[1]: "total_personas",
    cuadro15.columns[2]: "personas_asisten",
    cuadro15.columns[3]: "pct_asistencia"
})
df_asistencia = cuadro15[["region","total_personas","personas_asisten","pct_asistencia"]]

# --- Cuadro 16: Indicadores de educación (años promedio, etc.) ---
cuadro16 = cuadro16.rename(columns={
    "Total nacional": "region",
    cuadro16.columns[1]: "promedio_anios_escolaridad",
    cuadro16.columns[2]: "desviacion_escolaridad",
    cuadro16.columns[3]: "indice_educativo"
})
df_educacion = cuadro16[["region","promedio_anios_escolaridad","desviacion_escolaridad","indice_educativo"]]

# --- Cuadro 17: Uso de recursos educativos en línea ---
cuadro17 = cuadro17.rename(columns={
    "Total nacional": "region",
    cuadro17.columns[1]: "grupo_edad",
    cuadro17.columns[2]: "total_personas",
    cuadro17.columns[3]: "uso_recursos_online"
})
df_online = cuadro17[["grupo_edad","total_personas","uso_recursos_online"]]

# --- Cuadro 18: Hogares con Internet por región ---
cuadro18 = cuadro18.rename(columns={
    "Total nacional": "region",
    cuadro18.columns[1]: "total_hogares",
    cuadro18.columns[2]: "hogares_con_internet",
    cuadro18.columns[3]: "pct_hogares_internet"
})
df_internet_reg = cuadro18[["region","total_hogares","hogares_con_internet","pct_hogares_internet"]]

# ================================
# 3. Verificar shapes
# ================================
print("df_pc:", df_pc.shape)
print("df_internet:", df_internet.shape)
print("df_pc_edad:", df_pc_edad.shape)
print("df_asistencia:", df_asistencia.shape)
print("df_educacion:", df_educacion.shape)
print("df_online:", df_online.shape)
print("df_internet_reg:", df_internet_reg.shape)

# ================================
# 4. Unir datasets por región
# ================================

# Empezamos con df_pc
dataset = df_pc.copy()

# Merge con Internet (zona y región)
dataset = dataset.merge(
    df_internet[["region","hogares_con_internet","pct_hogares_internet"]],
    on="region", how="inner"
)

# Merge con asistencia escolar
dataset = dataset.merge(
    df_asistencia[["region","total_personas","personas_asisten","pct_asistencia"]],
    on="region", how="inner"
)

# Merge con indicadores de educación
dataset = dataset.merge(
    df_educacion,
    on="region", how="inner"
)

# Merge con Internet por región
dataset = dataset.merge(
    df_internet_reg[["region","hogares_con_internet","pct_hogares_internet"]],
    on="region", how="inner", suffixes=("_zona","_region")
)

# ================================
# 5. Guardar dataset final
# ================================
dataset.to_csv("dataset_brecha_digital.csv", index=False, encoding="utf-8-sig")

print("Dataset consolidado guardado como dataset_brecha_digital.csv")
print("Dimensiones finales:", dataset.shape)
print("Columnas:", dataset.columns.tolist())

"""ANALISIS"""

# Gráfico comparativo por región
# Excluir las últimas 3 filas and 'Cabecera' and 'Centros poblados y rural disperso' before plotting
filtered_dataset = dataset[:-3][~dataset[:-3]['region'].isin(['Cabecera', 'Centros poblados y rural disperso'])]

ax = filtered_dataset.plot(
    x="region",
    y=["pct_hogares_pc", "pct_hogares_internet_region"],
    kind="bar",
    figsize=(14,6),
    color = ['#1f77b4', '#ff7f0e'] # Use blue and orange colors
)

plt.title("Porcentaje de hogares con PC e Internet por región")
plt.ylabel("% Hogares")

# Etiquetas de regiones verticales
ax.set_xticklabels(filtered_dataset["region"], rotation=90, ha="center")

# Make legend labels more descriptive
ax.legend(["% Hogares con PC", "% Hogares con Internet"])


# Fuente del DANE como etiqueta del eje X
ax.set_xlabel("Fuente: DANE", fontsize=10, color="gray", labelpad=20)

plt.tight_layout()
plt.show()

dataset_limpio["brecha_pc_internet"] = (
    dataset_limpio["pct_hogares_internet_region"] - dataset_limpio["pct_hogares_pc"]
)

plt.figure(figsize=(12,6))
sns.barplot(
    x="region",
    y="brecha_pc_internet",
    hue="region",              # necesario para poder aplicar palette
    data=dataset_limpio,
    palette="coolwarm",
    legend=False               # quitamos la leyenda redundante
)
plt.xticks(rotation=90)
plt.title("Brecha entre hogares con Internet vs PC por región")
plt.ylabel("Diferencia porcentual (Internet - PC)")
plt.xlabel("Región")
plt.axhline(0, color="black", linestyle="--")
plt.tight_layout()
plt.show()

# Filtrar solo las filas que son regiones válidas
unwanted_regions = [
    "notas", "datos expandidos", "resultados en miles", "12", "16", "20", "24",
    "Fuente: DANE - Encuesta Nacional de Calidad de Vida",
    "Notas: \n- Datos expandidos con proyecciones de población 2005-2024 con base en el Censo General 2005, empalmados al 30 de junio del año de la encuesta.\n- Las estimaciones de necesidades básicas insatisfechas (NBI) se calculan con base en la metodología establecida en el Censo General 2005.\n- Los datos están sujetos a cambios por proyecciones de población o ajustes metodológicos.",
    "Actualizado el 24 de abril de 2025",
    "Cabecera",
    "Centros poblados y rural disperso"
]
dataset_limpio = dataset[~dataset["region"].isin(unwanted_regions)].copy()

# Create a combined bar and line chart
fig, ax1 = plt.subplots(figsize=(14, 7))

# Plotting the bars for pct_hogares_internet_region
sns.barplot(
    x="region",
    y="pct_hogares_internet_region",
    data=dataset_limpio,
    ax=ax1,
    color='#1f77b4' # Use blue color for bars
)
ax1.set_ylabel("Porcentaje de hogares con Internet", fontsize=12)
ax1.tick_params(axis='y')
ax1.set_xticklabels(dataset_limpio["region"], rotation=90, ha="center")

# Create a secondary y-axis for the line plot of pct_asistencia
ax2 = ax1.twinx()
sns.lineplot(
    x="region",
    y="pct_asistencia",
    data=dataset_limpio,
    ax=ax2,
    color='#ff7f0e', # Use orange color for the line
    marker="o",
    sort=False
)
ax2.set_ylabel("Porcentaje de asistencia escolar", fontsize=12, color="#ff7f0e") # Match line color
ax2.tick_params(axis='y', labelcolor="#ff7f0e") # Match line color


plt.title("Relación: Internet en el hogar vs Asistencia escolar por Región", fontsize=16)
plt.xlabel("Región", fontsize=12)
ax1.grid(True, linestyle='--', alpha=0.5)

# Improve legend - create handles for both plots
lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax2.legend(lines + lines2, ["% Hogares con Internet", "% Asistencia escolar"], loc="upper right")


plt.tight_layout()
plt.show()

#Relacionar acceso a TIC con años promedio de escolaridad

# Filtrar solo las filas que son regiones válidas
unwanted_regions = [
    "notas", "datos expandidos", "resultados en miles", "12", "16", "20", "24",
    "Fuente: DANE - Encuesta Nacional de Calidad de Vida",
    "Notas: \n- Datos expandidos con proyecciones de población 2005-2024 con base en el Censo General 2005, empalmados al 30 de junio del año de la encuesta.\n- Las estimaciones de necesidades básicas insatisfechas (NBI) se calculan con base en la metodología establecida en el Censo General 2005.\n- Los datos están sujetos a cambios por proyecciones de población o ajustes metodológicos.",
    "Actualizado el 24 de abril de 2025",
    "Cabecera",
    "Centros poblados y rural disperso"
]
dataset_limpio = dataset[~dataset["region"].isin(unwanted_regions)].copy()

# Relacionar con educación using a simple scatter plot
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,6))
sns.scatterplot(
    x="pct_hogares_pc",
    y="promedio_anios_escolaridad",
    data=dataset_limpio,
    hue="region", # Add hue for regions
    palette="viridis", # Use viridis palette
    s=100 # Increase point size
)
plt.title("Computador en el hogar vs Años de escolaridad promedio")
plt.xlabel("Porcentaje de hogares con PC")
plt.ylabel("Años promedio de escolaridad")
plt.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

#Índice compuesto de acceso TIC vs educación

#índice simple para ver “brecha digital educativa”.

# Filtrar solo las filas que son regiones válidas
unwanted_regions = [
    "notas", "datos expandidos", "resultados en miles", "12", "16", "20", "24",
    "Fuente: DANE - Encuesta Nacional de Calidad de Vida",
    "Notas: \n- Datos expandidos con proyecciones de población 2005-2024 con base en el Censo General 2005, empalmados al 30 de junio del año de la encuesta.\n- Las estimaciones de necesidades básicas insatisfechas (NBI) se calculan con base en la metodología establecida en el Censo General 2005.\n- Los datos están sujetos a cambios por proyecciones de población o ajustes metodológicos.",
    "Actualizado el 24 de abril de 2025",
    "Cabecera",
    "Centros poblados y rural disperso"
]
dataset_limpio = dataset[~dataset["region"].isin(unwanted_regions)].copy()

# Normalizar porcentajes entre 0 y 1
dataset_limpio["indice_tic"] = (
    dataset_limpio["pct_hogares_pc"]/100 + dataset_limpio["pct_hogares_internet_region"]/100
) / 2

# Relacionar con educación using a regression plot
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,6))
sns.regplot(
    x="indice_tic",
    y="indice_educativo",
    data=dataset_limpio,
    scatter_kws={'s':100, 'alpha':0.7, 'edgecolor':'k'}, # Add scatter plot customization
    line_kws={'color':'red'} # Color the regression line red
)
plt.title("Índice TIC vs Índice educativo con Línea de Regresión")
plt.xlabel("Índice TIC")
plt.ylabel("Índice educativo")
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Comparar % hogares con PC y uso online por edad
fig, ax1 = plt.subplots(1, 2, figsize=(14,6))

sns.barplot(
    data=df_pc_edad, x="grupo_edad", y="pct_hogares_pc",
    palette="Blues", ax=ax1[0]
)
ax1[0].set_title("Hogares con PC por grupo de edad")
ax1[0].set_ylabel("% Hogares con PC")
ax1[0].set_xlabel("Grupo de edad")
ax1[0].tick_params(axis='x', rotation=45)

sns.barplot(
    data=df_online, x="grupo_edad", y="uso_recursos_online",
    palette="Greens", ax=ax1[1]
)
ax1[1].set_title("Uso de recursos online por grupo de edad")
ax1[1].set_ylabel("% Uso recursos online")
ax1[1].set_xlabel("Grupo de edad")
ax1[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()